kube-prometheus-stack:
  namespaceOverride: prometheus
  grafana:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: public
        cert-manager.io/cluster-issuer: letsencrypt-grafana
        nginx.ingress.kubernetes.io/whitelist-source-range: 47.196.14.245/32
      hosts:
        - grafana-craigmiller160.ddns.net
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana-craigmiller160.ddns.net